# Generated by Django 4.2.6 on 2023-10-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_nickname',
            field=models.CharField(max_length=32, unique=True, verbose_name='telegram nickname'),
        ),
    ]
