# Generated by Django 4.2.6 on 2023-10-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='telegram-никнейм')),
                ('chat_id', models.PositiveIntegerField(unique=True, verbose_name='чат-id')),
            ],
            options={
                'verbose_name': 'телеграм пользователь',
                'verbose_name_plural': 'телеграм пользователи',
            },
        ),
    ]
